/**
 * 
 * Copyright 2010 Paul Scherrer Institute. All rights reserved.
 * 
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This code is distributed in the hope that it will be useful,
 * but without any warranty; without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this code. If not, see <http://www.gnu.org/licenses/>.
 * 
 */

package ch.psi.fda.ui.visualizer;

import ch.psi.pshell.plot.Plot;
import ch.psi.pshell.plot.LinePlotSeries;


/**
 * Metadata of a group of XYSeries.
 * This metadata holds the information needed by the DataVisualizer
 * to plot series.
 */
public class XYSeriesArrayDataFilter implements SeriesDataFilter {
	
	private final String idY;
	
	// Name of the series generated by this filter
	private String seriesName = "";
	
	// Number of series generated for this filter 
	private int count = 0;
	
	private int maxSeries = 10;

	// Offset of the array to plot
	private int offset = 0;
	// Size of the array to plot - size 0 means the complete array
	private int size = 0;
	
	// Plot the data of this filter goes to
	private final Plot plot;
	
	public XYSeriesArrayDataFilter(String idY, Plot plot){
		this.idY = idY;
		this.plot = plot;
	}
	
	/**
	 * @return the yId
	 */
	public String getIdY() {
		return idY;
	}

	/**
	 * @return the seriesName
	 */
	public String getSeriesName() {
		return seriesName;
	}

	/**
	 * @param seriesName the seriesName to set
	 */
	public void setSeriesName(String seriesName) {
		this.seriesName = seriesName;
	}

	private LinePlotSeries series = null;
        
        @Override
        public LinePlotSeries getSeries(){
            return series;
        }        
        
        public void setSeries(LinePlotSeries series){
            this.series=series;
        }        

        /**
	 * @return the count
	 */
	public int getCount() {
		return count;
	}

	/**
	 * @param count the count to set
	 */
	public void setCount(int count) {
		this.count = count;
	}

	/**
	 * @return the plot
	 */
	public Plot getPlot() {
		return plot;
	}

	/**
	 * Increment series count
	 */
	public void incrementCount(){
		count++;
	}

	/**
	 * @param maxSeries the maxSeries to set
	 */
	public void setMaxSeries(int maxSeries) {
		this.maxSeries = maxSeries;
	}

	/**
	 * @return the maxSeries
	 */
	public int getMaxSeries() {
		return maxSeries;
	}

	/**
	 * @return the offset
	 */
	public int getOffset() {
		return offset;
	}

	/**
	 * @param offset the offset to set
	 */
	public void setOffset(int offset) {
		this.offset = offset;
	}

	/**
	 * @return the size
	 */
	public int getSize() {
		return size;
	}

	/**
	 * @param size the size to set
	 */
	public void setSize(int size) {
		this.size = size;
	}
	
}
