/**
 * 
 * Copyright 2010 Paul Scherrer Institute. All rights reserved.
 * 
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This code is distributed in the hope that it will be useful,
 * but without any warranty; without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this code. If not, see <http://www.gnu.org/licenses/>.
 * 
 */

package ch.psi.fda.ui.visualizer;


import ch.psi.pshell.plot.LinePlot;
import ch.psi.pshell.plot.LinePlotSeries;


/**
 * Metadata of a group of XYSeries.
 * This metadata holds the information needed by the DataVisualizer
 * to plot series.
 */
public class XYSeriesDataFilter implements SeriesDataFilter{
	
	private final String idX;
	private final String idY;
	
	// Name of the series generated by this filter
	private String seriesName = "";
	
	// Number of series generated for this filter 
	private int count = 0;
        
        // Max number of points per series (additional appends make oldest value to be )
        private int maxNumberOfPoints=-1;
	
	// Plot the data of this filter goes to
	private final LinePlot plot;
		
	private boolean newseries = false;
        
        private LinePlotSeries series = null;
        @Override
        public LinePlotSeries getSeries(){
            return series;
        }
        public void setSeries(LinePlotSeries series){
            this.series=series;
        }        
	
	public XYSeriesDataFilter(String idX, String idY, LinePlot plot){
		this.idX = idX;
		this.idY = idY;
		this.plot = plot;
	}

	public String getIdX() {
		return idX;
	}
	public String getIdY() {
		return idY;
	}
	public String getSeriesName() {
		return seriesName;
	}
	public void setSeriesName(String seriesName) {
		this.seriesName = seriesName;
	}
	public int getCount() {
		return count;
	}
	public void setCount(int count) {
		this.count = count;
	}
	public LinePlot getPlot() {
		return plot;
	}
	public boolean isNewseries() {
		return newseries;
	}
	public void setNewseries(boolean newseries) {
		this.newseries = newseries;
	}
	public int getMaxNumberOfPoints() {
		return maxNumberOfPoints;
	}
	public void setMaxNumberOfPoints(int count) {
		this.maxNumberOfPoints = count;
	}	
}
