/**
 * 
 * Copyright 2010 Paul Scherrer Institute. All rights reserved.
 * 
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This code is distributed in the hope that it will be useful,
 * but without any warranty; without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this code. If not, see <http://www.gnu.org/licenses/>.
 * 
 */

package ch.psi.fda.ui.visualizer;

import ch.psi.pshell.plot.MatrixPlotSeries;
import ch.psi.pshell.plot.Plot;

public class XYZSeriesArrayDataFilter implements SeriesDataFilter {

	private final String idY;
	private final String idZ;
	
	// Name of the series generated by this filter
	private String seriesName = "";

	// Number of series generated for this filter 
	private int count = 0;
	
	// Plot the data of this filter goes to
	private final Plot plot;
	
	private boolean newseries = false;
	
	private final int size;
	private final int offset;
	
	public XYZSeriesArrayDataFilter(String idY, String idZ, int offset, int size, Plot plot){
		this.idY = idY;
		this.idZ = idZ;
		this.offset = offset;
		this.size = size;
		this.plot = plot;
	}

	public String getIdZ() {
		return idZ;
	}
	public String getSeriesName() {
		return seriesName;
	}
	public void setSeriesName(String seriesName) {
		this.seriesName = seriesName;
	}
	private MatrixPlotSeries series = null;
        
        @Override
        public MatrixPlotSeries getSeries(){
            return series;
        }        
        
        public void setSeries(MatrixPlotSeries series){
            this.series=series;
        }               
	public int getCount() {
		return count;
	}
	public void setCount(int count) {
		this.count = count;
	}
	public boolean isNewseries() {
		return newseries;
	}
	public void setNewseries(boolean newseries) {
		this.newseries = newseries;
	}
	public String getIdY() {
		return idY;
	}
	public int getOffset() {
		return offset;
	}
	public int getSize() {
		return size;
	}
	public Plot getPlot() {
		return plot;
	}
}
