/*
 *  Copyright (C) 2011 Paul Scherrer Institute
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * ChannelParameterMappingPanel.java
 *
 * Created on Feb 3, 2011, 2:16:48 PM
 */

package ch.psi.fda.ui.ce.panels.model;

import ch.psi.fda.ProcessorFDA;
import ch.psi.fda.ui.ce.panels.ComponentMetadata;
import ch.psi.fda.ui.ce.panels.PanelSupport;
import ch.psi.fda.ui.ce.panels.model.util.ModelUtil;
import ch.psi.fda.model.v1.VariableParameterMapping;
import ch.psi.fda.ui.ce.panels.DocumentAdapter;
import ch.psi.fda.ui.ce.panels.EditableComponent;
import ch.psi.fda.ui.ce.panels.ObjectProvider;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.HashMap;
import java.util.List;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author ebner
 */
public class GlobalVariableParameterMappingPanel extends javax.swing.JPanel implements ObjectProvider<VariableParameterMapping>, EditableComponent {

    private boolean modified = false;
    private VariableParameterMapping mapping;
    private PanelSupport panelSupport;
    

    public GlobalVariableParameterMappingPanel(){
        this(new VariableParameterMapping());
    }

    /** Creates new form ChannelParameterMappingPanel */
    public GlobalVariableParameterMappingPanel(final VariableParameterMapping mapping) {
        this.mapping = mapping;

        initComponents();
        
        ProcessorFDA.setIcon(jButton1, getClass().getResource("/ch/psi/fda/ui/ce/icons/plus.png"));        

        HashMap<Component, ComponentMetadata> managedFields = new HashMap<Component,ComponentMetadata>();
        managedFields.put(jTextFieldVariable, new ComponentMetadata(true));
        managedFields.put(jComboBoxType, new ComponentMetadata(true));

        this.panelSupport = new PanelSupport();
        this.panelSupport.analyze(managedFields);

        // Update view
        jTextFieldVariable.setText(mapping.getVariable());
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ModelUtil.getInstance().getId(mapping.getName()) }));


        // Establish bindings
        jTextFieldVariable.getDocument().addDocumentListener(new DocumentAdapter() {
            @Override
            public void valueChange(DocumentEvent de) {
                modified = true;
                mapping.setVariable(jTextFieldVariable.getText());
            }
        });
        jComboBoxType.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                modified = true;
                mapping.setName(ModelUtil.getInstance().getObject((String)jComboBoxType.getSelectedItem()));
            }
        });


        jButton1.setVisible(false);
        this.panelSupport.manage(this, managedFields, jButton1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldVariable = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jTextFieldVariable.setText("Variable");
        jTextFieldVariable.setPreferredSize(new java.awt.Dimension(80, 28));
        jPanel1.add(jTextFieldVariable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setLabelFor(jComboBoxType);
        jLabel1.setText("Variable:");
        jPanel1.add(jLabel1);

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none" }));
        jComboBoxType.setToolTipText("Id to map this variable");
        jComboBoxType.setName("Type"); // NOI18N
        jComboBoxType.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxTypePopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel1.add(jComboBoxType);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/fda/ui/ce/icons/plus.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTypePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxTypePopupMenuWillBecomeVisible
        // Get selected item
        Object o = jComboBoxType.getSelectedItem();
        // Update the possible options
        List<String> li = ModelUtil.getInstance().getGlobalVariables();
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(li.toArray(new String[li.size()])));
        // Set the item selected that was selected before
        jComboBoxType.setSelectedItem(o);
    }//GEN-LAST:event_jComboBoxTypePopupMenuWillBecomeVisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldVariable;
    // End of variables declaration//GEN-END:variables

    @Override
    public VariableParameterMapping getObject() {
        return mapping;
    }

    /**
     * Update ID's shown in the combo box
     */
    public void updateIds(){
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ModelUtil.getInstance().getId(mapping.getName()) }));
    }

    @Override
    public boolean modified() {
        boolean m = modified;
        modified = false;
        return m;
    }

    @Override
    public void clearModified() {
        modified = false;
    }
}
