/*
 *  Copyright (C) 2011 Paul Scherrer Institute
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuardConditionPanel.java
 *
 * Created on Jan 25, 2011, 3:17:21 PM
 */

package ch.psi.fda.ui.ce.panels.model;

import ch.psi.fda.ProcessorFDA;
import ch.psi.fda.ui.ce.panels.ComponentMetadata;
import ch.psi.fda.ui.ce.panels.PanelSupport;
import ch.psi.fda.model.v1.GuardCondition;
import ch.psi.fda.ui.ce.panels.DocumentAdapter;
import ch.psi.fda.ui.ce.panels.EditableComponent;
import ch.psi.fda.ui.ce.panels.ObjectProvider;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.HashMap;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author ebner
 */
public class GuardConditionPanel extends javax.swing.JPanel implements ObjectProvider<GuardCondition>, EditableComponent {

    private boolean modified = false;
    private GuardCondition condition;
    private PanelSupport panelSupport;

    public GuardConditionPanel() {
        this(new GuardCondition());
    }

    /** Creates new form GuardConditionPanel */
    public GuardConditionPanel(final GuardCondition condition) {
        this.condition = condition;

        initComponents();
        
        ProcessorFDA.setIcon(jButton1, getClass().getResource("/ch/psi/fda/ui/ce/icons/plus.png"));        

        HashMap<Component, ComponentMetadata> managedFields = new HashMap<Component,ComponentMetadata>();
        managedFields.put(jTextFieldChannel, new ComponentMetadata(true));
        managedFields.put(jTextFieldValue, new ComponentMetadata(true));
        managedFields.put(jComboBoxType, new ComponentMetadata(false, new GuardCondition().getType()));

        this.panelSupport = new PanelSupport();
        this.panelSupport.analyze(managedFields);


        // Update view
        jTextFieldChannel.setText(condition.getChannel());
        jTextFieldValue.setText(condition.getValue());
        jComboBoxType.setSelectedItem(condition.getType());


        // Establish bindings
        jTextFieldChannel.getDocument().addDocumentListener(new DocumentAdapter() {
            @Override
            public void valueChange(DocumentEvent de) {
                modified = true;
                condition.setChannel(panelSupport.getRealFieldValue(jTextFieldChannel));
            }
        });
        jTextFieldValue.getDocument().addDocumentListener(new DocumentAdapter() {
            @Override
            public void valueChange(DocumentEvent de) {
                modified = true;
                condition.setValue(jTextFieldValue.getText());
            }
        });
        jComboBoxType.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                modified = true;
                condition.setType((String) jComboBoxType.getSelectedItem());
            }
        });


        this.panelSupport.manage(this, managedFields, jButton1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldChannel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jTextFieldChannel.setText("Guard channel");
        jTextFieldChannel.setToolTipText("Channel Name");
        jTextFieldChannel.setName("Channel"); // NOI18N
        jTextFieldChannel.setPreferredSize(new java.awt.Dimension(180, 28));
        jPanel1.add(jTextFieldChannel);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setLabelFor(jTextFieldValue);
        jLabel2.setText("Value:");
        jPanel1.add(jLabel2);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/psi/fda/ui/ce/panels/model/Bundle"); // NOI18N
        jTextFieldValue.setToolTipText(bundle.getString("GuardConditionPanel.jTextFieldValue.toolTipText")); // NOI18N
        jTextFieldValue.setName("Value"); // NOI18N
        jTextFieldValue.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel1.add(jTextFieldValue);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setLabelFor(jComboBoxType);
        jLabel3.setText("Type:");
        jPanel1.add(jLabel3);

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<default>", "Double", "Integer", "String" }));
        jComboBoxType.setName("Type"); // NOI18N
        jPanel1.add(jComboBoxType);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/psi/fda/ui/ce/icons/plus.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldChannel;
    private javax.swing.JTextField jTextFieldValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public GuardCondition getObject() {
        return condition;
    }

    @Override
    public boolean modified() {
        boolean m = modified;
        modified = false;
        return m;
    }

    @Override
    public void clearModified() {
        modified = false;
    }
}
