/*
 *  Copyright (C) 2011 Paul Scherrer Institute
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * RegionPositionerPanel.java
 *
 * Created on Jan 18, 2011, 11:21:42 AM
 */

package ch.psi.fda.ui.ce.panels.model;

import ch.psi.fda.ui.ce.panels.CollapsibleListContainer;
import ch.psi.fda.ui.ce.panels.ComponentMetadata;
import ch.psi.fda.model.v1.Region;
import ch.psi.fda.model.v1.RegionPositioner;
import ch.psi.fda.ui.ce.panels.ObjectProvider;

/**
 *
 * @author ebner
 */
public class RegionPositionerPanel extends javax.swing.JPanel implements ObjectProvider<RegionPositioner> {

    private RegionPositioner positioner;

    public RegionPositionerPanel() {
        this(new RegionPositioner());
    }

    /** Creates new form RegionPositionerPanel */
    public RegionPositionerPanel(RegionPositioner positioner) {
        
        if(positioner.getId() == null || positioner.getId().equals("")){
            positioner.setId(IdGenerator.generateId());
        }
        this.positioner = positioner;

        initComponents();

        // Update view
        // -
        // Establish bindings
        // -
        
        collapsibleListContainer1.setHeader("Regions");
        collapsibleListContainer1.setName("Regions");
        collapsibleListContainer1.setIcon("list_num");

        discreteStepPositionerPanel1.getPanelSupport().addComponent(collapsibleListContainer1, new ComponentMetadata(false));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discreteStepPositionerPanel1 = new DiscreteStepPositionerPanel(positioner);
        collapsibleListContainer1 = new CollapsibleListContainer<Region>(new RegionListItemProvider(positioner.getRegion()));

        discreteStepPositionerPanel1.setPreferredSize(new java.awt.Dimension(214, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(discreteStepPositionerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, Short.MAX_VALUE)
            .addComponent(collapsibleListContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(discreteStepPositionerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collapsibleListContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.psi.fda.ui.ce.panels.CollapsibleListContainer collapsibleListContainer1;
    private ch.psi.fda.ui.ce.panels.model.DiscreteStepPositionerPanel discreteStepPositionerPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public RegionPositioner getObject() {
        return positioner;
    }

}
